# 16 Pre-Class Assignment: Singular Value Decomposition

## Goals for today's pre-class assignment 

</p>

1. [Video On Singular Value Decomposition](#Video_On_Signular_Value_Decomposition)
1. [Diagonalizing a Square Matrix](#Diag)
1. [Singular Value Decomposition](#SVD)

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
sym.init_printing()

---
<a name="Video_On_Signular_Value_Decomposition"></a>

# 1. Video On Signular Value Decomposition

Calculating the eigenvaluse and eigenvectors of a matrix requires that the matrix is square ($n \times n$). Think of SVD as a way to get similar information from a non-square matrix.

This video is a little longer than most videos.  I recommend reading the questions first and then watching the video and following along with the provided code examples.

In [ ]:
from IPython.display import YouTubeVideo
YouTubeVideo("EfZsEFhHcNM",width=640,height=360)

---
<a name="Diag"></a>

## 2. Diagonalizing a Square Matrix

As we saw in previous assignments, a square matrix $$n\times n, whose eigenvectors form a basis of $\mathbb R^n$ is diagonalizable.
Consider the following matrix provided in the above video (~1:50 into the video)

In [2]:
A = np.matrix([[1,1,3], [-3, -5, -3], [3, 3, 1]])
sym.Matrix(A)

⎡1   1   3 ⎤
⎢          ⎥
⎢-3  -5  -3⎥
⎢          ⎥
⎣3   3   1 ⎦

&#9989; <font color=red>**DO THIS:**</font> Calculate the Eigenvalues and Eigenvectors for the above matrix $A$. name the eigenvalues (vals) and the eigenvectors (vecs)

In [9]:
##Put your code here

vals, vecs = np.linalg.eig(A)

The following code sorts the eigenvectors based on the ordering of the eigenvalues. It does this using the argsort algorithm which puts the values in ascending order.  The ```[::-1]``` notation reverses the order of the indexes.  We will put the sorted vectors into a matrix called $P$

In [10]:
idx = vals.argsort()[::-1]   
vals = vals[idx]
vecs = vecs[:,idx]


print(idx)
V = vecs
sym.Matrix(V)

print(V)

P = vecs
sym.Matrix(P)

[0 2 1]
[[-7.17666340e-01 -7.07106781e-01  3.07751722e-01]
 [ 4.92420057e-01 -8.32667268e-16  6.72788554e-01]
 [-4.92420057e-01  7.07106781e-01 -6.72788554e-01]]


⎡-0.717666339515337   -0.707106781186547    0.307751722477118 ⎤
⎢                                                             ⎥
⎢0.492420057027868   -8.32667268468866e-16  0.672788554195286 ⎥
⎢                                                             ⎥
⎣-0.492420057027868    0.707106781186548    -0.672788554195286⎦

The following code generates a matrix of the same size as $A$ and puts the eigenvalues on the diagonals. 

In [11]:
D = np.zeros(A.shape)
for i in range(len(vals)):
    D[i,i] = vals[i]
sym.Matrix(D)

⎡2.37228132326901  0.0          0.0       ⎤
⎢                                         ⎥
⎢      0.0         -2.0         0.0       ⎥
⎢                                         ⎥
⎣      0.0         0.0   -3.37228132326901⎦

&#9989; <font color=red>**DO THIS:**</font> Show that $A=PDP^{-1}$

In [14]:
#Put your answer here
P_inv = np.linalg.inv(P)

print(P*D*P_inv)
print('')
print(A)

[[ 1.  1.  3.]
 [-3. -5. -3.]
 [ 3.  3.  1.]]

[[ 1  1  3]
 [-3 -5 -3]
 [ 3  3  1]]


In [15]:
###Answer###

P*D*np.linalg.inv(P)-A
###Answer###

matrix([[ 8.88178420e-16,  1.11022302e-15, -1.33226763e-15],
        [ 0.00000000e+00, -8.88178420e-16,  0.00000000e+00],
        [ 8.88178420e-16,  2.22044605e-15,  8.88178420e-16]])

&#9989; <font color=red>**DO THIS:**</font> Show that $A^{10}=PD^{10}P^{-1}$. I.e. multiply A by itself 10 times and then taking $\sigma^{10}$ for each of the eigenvalues in the diagonal of $D$.

In [18]:
print(A**10)
print('')
print(P*D**10*P_inv)

[[  49735  112969   48711]
 [  96387  242509   96387]
 [ -96387 -241485  -95363]]

[[  49735.  112969.   48711.]
 [  96387.  242509.   96387.]
 [ -96387. -241485.  -95363.]]


&#9989; <font color=red>**QUESTION 1:**</font> What is the estimated complexity of multiplying an arbitrary $n\times n$ matrix by itself $m$ times? (Hint: both $m$ and $n$ should be included in your Big-O notation answer). 

O(N)^2 * O(M)

&#9989; <font color=red>**QUESTION 2:**</font> What is the estimated complexity (Big-O) of diagonalizing an $n \times n$ symmetric matrix? i.e. what is the complexity of decomposing $A$ into $PDP^{-1}$?

O(N)^2

&#9989; <font color=red>**QUESTION 3:**</font> What is the estimated complexity (Big-O) of multiplying a diagonlized $n \times n$ matrix by itself $m$ times? i.e. you already have $A=PDP^{-1}$ calculated what does it cost to calculate $A^m$?

O(N)^2 * O(M)

### Inverse of an orthonormal matrix $U$ is $U^\top$
    
Caluclate the $P$ matrix for the following matrix $A$ such that $A=PDP^{-1}$

In [27]:
A = np.matrix([[6,-2,-1],[-2,6,-1], [-1,-1,5]])
sym.Matrix(A)

P = sym.Matrix(A).diagonalize()

P[0]

⎡1  -1  -1⎤
⎢         ⎥
⎢1  -1  1 ⎥
⎢         ⎥
⎣1  2   0 ⎦

&#9989; <font color=red>**DO THIS:**</font> Check the columns of $P$. Are they orthogonal?

Yes

&#9989; <font color=red>**DO THIS:**</font> Show that in this special case (Where $A$ is symmetric) $A=PDP^\top$ with a special $P$.

Put your answer here

&#9989; <font color=red>**QUESTION 4:**</font> What do you need to do to invert an arbitrary $n \times n$ matrix?

Put your answer here.

&#9989; <font color=red>**QUESTION 5:**</font> What do you need to do to invert a $n \times n$ **orthonormal** matrix?

Put your answer here.

---
<a name="SVD"></a>

## 3. Singular Value Decomposition (SVD) 

SVD is not restricted to diagonalizable matrices, for example it can be applied to square non-diagonalizable matrices, as well as to non-square matrices.

Now consider the non-square $n \times m$ matrix $A$

In [20]:
A = np.matrix([[4, 11, 14], [8, 7, -2]])

sym.Matrix(A)

⎡4  11  14⎤
⎢         ⎥
⎣8  7   -2⎦

The following code calculates $A^\top A=VDV^\top$:

In [21]:
sym.Matrix(A.T*A)

⎡80   100  40 ⎤
⎢             ⎥
⎢100  170  140⎥
⎢             ⎥
⎣40   140  200⎦

In [22]:
eigvals, eigvec = np.linalg.eig(A.T*A)
idx = eigvals.argsort()[::-1]   
eigvals = eigvals[idx]
eigvec = eigvec[:,idx]

V = eigvec
sym.Matrix(V)

⎡-0.333333333333334  -0.666666666666666  -0.666666666666667⎤
⎢                                                          ⎥
⎢-0.666666666666666  -0.333333333333333  0.666666666666666 ⎥
⎢                                                          ⎥
⎣-0.666666666666667  0.666666666666667   -0.333333333333333⎦

&#9989; <font color=red>**DO THIS:**</font>  Calculate $AA^\top=UDU^\top$:

In [23]:
#Put your answer here

The following code calculates $\Sigma$ by putting the singular values on the diagonal of an $n \times m$ zero matrix: 

In [24]:
np.sqrt(np.abs(eigvals))*np.identity(1)

E = np.zeros(A.shape)

for i in range(len(eigvals)):
    E[i,i] = np.sqrt(eigvals[i])
    
sym.Matrix(E)

<ipython-input-24-75576e06682f>:6: RuntimeWarning: invalid value encountered in sqrt
  E[i,i] = np.sqrt(eigvals[i])


IndexError: index 2 is out of bounds for axis 0 with size 2

&#9989; <font color=red>**DO THIS:**</font>  Verify that $A=U \Sigma V^\top$ or $A=-U\Sigma V^\top$. 

**Note:** $\sigma_i^2=\lambda_i$ is an eigenvalue of $A^TA$ and also $AA^T$. When we put the singular values in descending order, $\sigma_1\geq \sigma_2 \geq \dots \sigma_r>0$, they are uniquely determined.

In [ ]:
#Put your answer here

---------
### Congratulations, we're done!
